language: python
dist: focal
python:
  - "3.10"

install:
  - python3 -m pip install python-telegram-bot
  - python -m pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install telebot pymongo aiohttp
  - pip install pymongo python-telegram-bot pyTelegramBotAPI certifi
script:
  - chmod +x *
  - travis_wait 120 python3 omg.py


